platform :ios, '13.0'

flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, '.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  install_all_flutter_pods(flutter_application_path)
end
