# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics disables by default for CI builds like CodeMagic
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Standard Flutter Pod setup
require_relative '../flutter_export_environment'
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
